# jupyter-v1
version: '2'
services:
  my-math-app:
    image: jupyter:mini-v1
    container_name: jupyter-v1
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - "/data/jupyter_work:/jupyter_work"

# useing
# docker-compose -f docker-compose-miniconda-jupyter-v1.yml up -d